version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
